Foof

diff --git a/.github/workflows/release_common.yaml b/.github/workflows/release_common.yaml
--- a/.github/workflows/release_common.yaml
+++ b/.github/workflows/release_common.yaml
@@ -35,13 +35,17 @@ on:
         type: boolean
         required: false
         default: false
+      bcr_bazel_test_command:
+        description: 'The bazel test command to run before publishing to BCR'
+        type: string
+        required: false
       create_github_release:
         description: 'Create a GitHub release (which also creates a git tag)'
         type: boolean
         required: false
         default: false
-      continue_if_release_exists:
-        description: 'Continue the workflow even if the GitHub release already exists'
+      continue_if_tag_exists:
+        description: 'Continue the workflow even if the git tag already exists'
         type: boolean
         required: false
         default: false
@@ -111,80 +115,62 @@ jobs:
           SONATYPE_PASSWORD_TOKEN: ${{ secrets.SONATYPE_PASSWORD_TOKEN }}
           MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
 
-
-  # create_github_release:
-  #   if: ${{ inputs.create_github_release }}
-  #   permissions:
-  #     contents: write
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
-
-  #     - name: Check if release exists
-  #       id: check_release
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       run: |
-  #         set +e # Do not exit on error. gh release view will return non-zero exit code if the release does not exist.
-  #         gh release view ${{ inputs.version }} > /dev/null 2>&1
-  #         if [ $? -eq 0 ]; then
-  #           if [[ "${{ inputs.continue_if_release_exists }}" == "true" ]]; then
-  #             echo "Release ${{ inputs.version }} already exists. Skipping release creation."
-  #             echo "github_release_exists=true" >> $GITHUB_OUTPUT
-  #           else
-  #             echo "Error: Release ${{ inputs.version }} already exists."
-  #             echo "Set 'continue_if_release_exists' to true if you want to continue with the exising release."
-  #             exit 1
-  #           fi
-  #         else
-  #           echo "Release ${{ inputs.version }} does not exist."
-  #           echo "github_release_exists=false" >> $GITHUB_OUTPUT
-  #         fi
-
-  #     - name: Build archive and Create Github Release
-  #       if: ${{ steps.check_release.outputs.github_release_exists == 'false' }}
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       run: |
-  #         set +x
- 
-  #         echo "Archive built successfully."
-
-  #         echo "Creating GitHub release ${tag}"
-  #         # This will also create a git tag if it does not exist.
-  #         gh release create "${tag}" --generate-notes
-  #         echo "GitHub release ${tag} created successfully."
-
-  #         echo "Uploading archive ${archive} to release ${tag}"
-  #         gh release upload "${tag}" "${archive}"
-  #         echo "Archive uploaded successfully."
   create_git_tag:
     runs-on: ubuntu-latest
     permissions:
       # Required for creating and pushing git tags.
       contents: write
-
     steps:
       - name: Checkout current commit
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-
-      - name: Create Git Tag
+      - name: Check and Create Git Tag
         run: |
+          TAG_NAME="${{ inputs.version }}"
+          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
+            echo "Tag '$TAG_NAME' already exists."
+            if [[ "${{ inputs.continue_if_tag_exists }}" == "true" ]]; then
+              echo "Continuing workflow as 'continue_if_tag_exists' is true. Skipping tag creation."
+              exit 0
+            else
+              echo "Error: Tag '$TAG_NAME' already exists and 'continue_if_tag_exists' is false. Aborting."
+              exit 1
+            fi
+          fi
+
           git config --local user.email "j2cl-github-bot@github.com"
           git config --local user.name "J2CL GitHub Bot"
-          git tag -a "${{ inputs.version }}" -m "Release ${{ inputs.version }}"
-          git push origin "${{ inputs.version }}"
+          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
+          git push origin "$TAG_NAME"
+
+  run_tests:
+    runs-on: ubuntu-latest
+    needs: create_git_tag
+    steps:
+      - name: Checkout tagged commit
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ inputs.version }}
+      - name: Setup Java
+        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
+        with:
+          java-version: '21'
+          distribution: 'zulu'
+          java-package: jdk
+      - name: Setup Bazel
+        uses: bazelbuild/setup-bazelisk@v3
+      - name: Run CI tests
+        run: ./build_test.sh "CI"
 
   release:
-    needs: create_git_tag
+    needs: run_tests
     if: ${{ inputs.create_github_release }}
-    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.2
+    uses: bazel-contrib/.github/workflows/release_ruleset.yaml@v7.2.2
     with:
       prerelease: false
       release_files: ${{ github.event.repository.name }}-*.tar.gz
       tag_name: ${{ inputs.version }}
-      bazel_test_command: "bazel test transpiler/javatests/com/google/j2cl/integration/java/emptyclass/..."
-
+      bazel_test_command: ${{ inputs.bcr_bazel_test_command }}
+a
   publish_to_bcr:
     if: ${{ inputs.publish_to_bcr }}
     needs: release
@@ -193,7 +179,6 @@ jobs:
       tag_name: ${{ inputs.version }}
       registry_fork: j2cl-github-bot/bazel-central-registry
       attest: true
-      draft: true
       author_name: j2cl-github-bot
       author_email: j2cl-github-bot@google.com
     permissions:
