test

diff --git a/.github/workflows/release_common.yaml b/.github/workflows/release_common.yaml
--- a/.github/workflows/release_common.yaml
+++ b/.github/workflows/release_common.yaml
@@ -68,7 +68,12 @@ jobs:
     steps:
       - name: Checkout current commit
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-
+      - name: Check if on Master Branch
+        run: |
+          if ! git merge-base --is-ancestor "${{ github.ref }}" "refs/heads/master"; then
+            echo "Error: Releases can only be created from commits that are on the 'master' branch."
+            exit 1
+          fi
       - name: Check and Create Git Tag
         run: |
           TAG_NAME="${{ inputs.version }}"
