Update release_common.yaml

diff --git a/.github/workflows/release_common.yaml b/.github/workflows/release_common.yaml
--- a/.github/workflows/release_common.yaml
+++ b/.github/workflows/release_common.yaml
@@ -71,27 +71,34 @@ jobs:
       - name: Check and Create Git Tag
         run: |
           TAG_NAME="${{ inputs.version }}"
-          git status
-          ls -a .git/refs/tags/
-          if git show-ref --verify --tags --quiet "refs/tags/${TAG_NAME}" >/dev/null 2>&1; then
-            echo "Tag '$TAG_NAME' already exists."
-            if [[ "${{ inputs.continue_if_tag_exists }}" == "true" ]]; then
-              echo "Continuing workflow as 'continue_if_tag_exists' is true. Skipping tag creation."
-              exit 0
+          # Get all remote refs matching the TAG_NAME
+          ALL_REFS=$(git ls-remote origin "$TAG_NAME")
+
+          # Check if any refs were found and if we should continue
+          if [ -n "${ALL_REFS}" ]; then
+            # Check if this is a tag reference
+            if echo "${ALL_REFS}" | grep -q "refs/tags/${TAG_NAME}"; then
+              echo "Tag '$TAG_NAME' already exists."
+              if [[ "${{ inputs.continue_if_tag_exists }}" == "true" ]]; then
+                echo "Continuing workflow as 'continue_if_tag_exists' is true. Skipping tag creation."
+                exit 0
+              else
+                echo "Error: Tag '$TAG_NAME' already exists and 'continue_if_tag_exists' is false. Aborting."
+                exit 1
+              fi
             else
-              echo "Error: Tag '$TAG_NAME' already exists and 'continue_if_tag_exists' is false. Aborting."
+              echo "A ref with name '${TAG_NAME}' exists but is not a tag (e.g., a branch). Aborting."
               exit 1
             fi
-          elif git rev-parse "${TAG_NAME}" >/dev/null 2>&1; then
-            echo "Error: a ref named '$TAG_NAME' already exists and is not a tag. Aborting."
-            exit 1
           fi
+
+          echo "Creating tag '$TAG_NAME'"
 
           git config --local user.email "j2cl-github-bot@github.com"
           git config --local user.name "J2CL GitHub Bot"
           git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
           git push origin "$TAG_NAME"
-
+          
   publish_to_sonatype:
     runs-on: ubuntu-latest
     if: ${{ inputs.publish_to_sonatype }}
